### ISSUE TITLE
v2024.8.1  not building on nipkgs stable

### ISSUE THREAD

**Issue by TuxCoder** [nix-community/authentik-nix#32]
Hello,

Not sure if this is a bug or simply not supported.

The latest release does not build on the stable nixpkgs channel.

```
       error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "buildGo123Module" at /nix/store/x0w41dsd2xpgxx29kgpaihmk2bsdpzxd-source/components/gopkgs.nix:4, did you mean "buildGo121Module" or "buildGo122Module"?'
```
Hier in this file:
https://github.com/nix-community/authentik-nix/blob/main/components/gopkgs.nix#L9

because `go_1_23` is only in nixpkgs-unstable

If stable branch should not be supported,
you can close this issue.

Also thanks for the nice flake!

**Comment by TuxCoder** [comment]
ah I see, upstream also updated to go1.23
https://github.com/goauthentik/authentik/blob/main/go.mod

probably add a note in the readme that this flake only builds against unstable,
as authentik is not really stable yet?

**Comment by WilliButz** [comment]
> If stable branch should not be supported,
> you can close this issue.

Yes, currently is is not. This was the case with previous releases, where either go or node were bumped in upstream authentik, but not available from the NixOS stable branch.
Not updating the comment was an oversight on my end: https://github.com/nix-community/authentik-nix/blob/main/flake.nix#L16

> probably add a note in the readme that this flake only builds against unstable,

Yes, I really should do that as it came up a few times already. It seems to be quite common to simply override any inputs of ones own flake inputs via `follows` so that the personal flake lock has as little "duplicate" locked inputs as possible.

While this has some obvious appeal, you also have no guarantees that the input overrides you put in are compatible with the flake itself or even with each other. Due to authentik having a huge number of dependencies, one can easily break a working build by overriding flake inputs (also in #33).

The most important inputs for this flake are `nixpkgs` and `poetry2nix`. They need to be compatible with both each other and this flake. **When overriding any of the two via `follows`, there is no guarantee for a working build.**

The dependencies locked in the flake.lock of this repository _should_ always provide a successful build, if that is not the case I'd consider it an issue. But using custom flake input overrides is not something I can support.

> as authentik is not really stable yet?

I would say it has been for quite a while, especially the upstream project. With this flake I cannot remember a version upgrade that went badly wrong.

**Comment by TuxCoder** [comment]
Thanks for the replay,

will test with non overrides but currently a bit busy, so sorry for the delay

**Comment by TuxCoder** [comment]
So tested now without override the inputs,
works like a charm :)
Also if I interpret the code correctly only the program is build from the the unstable branch.
rest of the system stays on the stable channel, that is fine for me.
